<a href="https://colab.research.google.com/github/tigromol/CoelusTest/blob/master/Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
def only_ones(list):
  for i in list:
    if i > 1:
      return False
  return True
def vector_tester(vector, size):
  print(np.reshape(vector,size))

In [0]:
def init_rect(size, field):
  area = field[0]*field[1]
  hor_step = field[0]-size[0]+1
  vert_step = field[1] - size[1]+1
  init_matr = np.zeros(((hor_step) * (vert_step),area))
  template = (([1] * size[0] + [0]*(field[0]-size[0]))*size[1])
  i=0
  for j in range(vert_step):
    for k in range(hor_step):
      k = ([0]*field[0])*j + [0]*k + template[:len(template)-(field[0]-size[0])] #template for iteration
      init_matr[i] = k + [0]*(area-len(k))
      i += 1
  return init_matr  
  

In [0]:
def vect(list1,list2):
  new_vect = np.zeros((list1.shape[0] * list2.shape[0],list1.shape[1]))
  k = 0
  for i in list1:
    for j in list2:
      new_vect[k] = i+j
      k+=1
  return filt(new_vect)
def filt(matrice):
  bool_arr = np.array([only_ones(row) for row in matrice])
  return(matrice[bool_arr])

In [135]:
tmp = init_rect((2,2),(3,5))
tmp1 = init_rect((2,2),(3,5))
vector_tester(vect(tmp,tmp1)[4],(5,3))

[[0. 1. 1.]
 [0. 1. 1.]
 [1. 1. 0.]
 [1. 1. 0.]
 [0. 0. 0.]]
